### ISSUE TITLE
OK, you got the cert. Now what?

### ISSUE THREAD

**Issue by DavidPhillipOster** [fractalspace/tlsclient#1]
I'm still confused.

Once you've gotten the certificate, how do you validate it?

Once you've validated it, How do you write an HTTP "Get " to the remote server, and how do you read the response?

**Comment by fractalspace** [comment]
So this little example only demonstrates an SSL handshake, ability to initiate secure connection over TCP socket, using OpenSSL APIs'. A practical tls client will also do:
- Ability to validate server certificate (this will require a locally available issuer certificate or CA)
- Send and receive arbitrary data to/from the server over the tls socket (e.g client code will create an "http GET" request chunk of text and send it over the socket).
